const movies = [
    {title: 'Iron Man',
    image: "images/iron-man.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Incredible Hulk',
    image: "images/incredible-hulk.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Iron Man 2',
    image: "images/iron-man-2.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Thor',
    image: "images/thor.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Captain America: The First Avenger',
    image: "images/captain-america-the-first-avenger.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Avengers',
    image: "images/avengers.jpg",
    hints: ['q1','q2','q3']},
    {title: "Iron Man 3",
    image: "images/iron-man-3.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Thor: The Dark World',
    image: "images/thor-the-dark-world.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Captain America: The Winter Soldier',
    image: "images/captain-america-the-winter-soldier.jpg",
    hints: ['q1','q2','q3']},
    {title: "Guardians of the Galaxy",
    image: "images/guardians-of-the-galaxy.jpg",
    hints: ['q1','q2','q3']},
    {title: "Avengers: Age of Ultron",
    image: "images/avengers-age-of-ultron.jpg",
    hints: ['q1','q2','q3']},
    {title: "Ant Man",
    image: "images/ant-man.jpg",
    hints: ['q1','q2','q3']},
    {title: "Doctor Strange",
    image: "images/doctor-strange.jpg",
    hints: ['q1','q2','q3']},
    {title: "Captain America: Civil War",
    image: "images/captain-america-civil-war.jpg",
    hints: ['q1','q2','q3']},
    {title: "Guardians of the Galaxy vol.2",
    image: "images/guardians-of-the-galaxy-vol2.jpg",
    hints: ['q1','q2','q3']},
    {title: "Spider-man: Homecoming",
    image: "images/spiderman-homecoming.jpg",
    hints: ['q1','q2','q3']},
    {title: "Thor: Ragnarok",
    image: "images/thor-ragnarok.jpg",
    hints: ['q1','q2','q3']},
    {title: "Black Panther",
    image: "images/black-panther.jpg",
    hints: ['q1','q2','q3']},
    {title: "Avengers: Infinity War",
    image: "images/avengers-infinity-war.jpg",
    hints: ['q1','q2','q3']},
    {title: "Ant Man and the Wasp",
    image: "images/ant-man-and-the-wasp.jpg",
    hints: ['q1','q2','q3']},
    {title: "Captain Marvel",
    image: "images/captain-marvel.jpg",
    hints: ['q1','q2','q3']},
    {title: "Avengers: Endgame",
    image: "images/avengers-endgame.jpg",
    hints: ['q1','q2','q3']},
    {title: "Spider-man: Far From Home",
    image: "images/spiderman-far-from-home.jpg",
    hints: ['q1','q2','q3']},
    {title: "Black Widow",
    image: "images/black-widow.jpg",
    hints: ['q1','q2','q3']},
    {title: "Shang-Chi and the Legend of the Ten Rings",
    image: "images/shang-chi-and-the-legend-of-the-ten-rings.jpg",
    hints: ['q1','q2','q3']},
    {title: "Eternals",
    image: "images/eternals.jpg",
    hints: ['q1','q2','q3']},
    {title: "Spider-Man: No Way Home",
    image: "images/spiderman-no-way-home.jpg",
    hints: ['q1','q2','q3']},
    {title: "Doctor Strange in the Multiverse of Madness",
    image: "images/doctor-strange-in-the-multiverse-of-madness.jpg",
    hints: ['q1','q2','q3']},
    {title: "Thor: Love and Thunder",
    image: "images/thor-love-and-thunder.jpg",
    hints: ['q1','q2','q3']},
    {title: "Black Panther: Wakanda Forever",
    image: "images/black-panther-wakanda-forever.jpg",
    hints: ['q1','q2','q3']},
];
