const movies = [
    {title: 'Iron Man',
    image: "images/iron-man.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Incredible Hulk',
    image: "images/incredible-hulk.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Iron Man 2',
    image: "images/iron-man-2.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Thor',
    image: "images/thor.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Captain America: The First Avenger',
    image: "images/captain-america-the-first-avenger.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Avengers',
    image: "images/avengers.jpg",
    hints: ['q1','q2','q3']},
    {title: "Iron Man 3",
    image: "images/iron-man-3.jpg",
    hints: ['q1','q2','q3']},
    {title: 'Thor: The Dark World',
    image: "images/thor-the-dark-world.jpg",
    hints: ['q1','q2','q3']},
    {title: "Ant Man",
    image: "images/ant-man.jpg",
    hints: ['q1','q2','q3']}
];
