const movies = [
    {title: 'Iron Man',
    image: "images/iron-man.jpg",
    hints: ['First MCU movie.','Starring Jeff Bridges','Quote: I am Iron Man.']},
    {title: 'Incredible Hulk',
    image: "images/incredible-hulk.jpg",
    hints: ['Main character almost always wears purple pants.','The green guy.','Quote: SMASH!']},
    {title: 'Iron Man 2',
    image: "images/iron-man-2.jpg",
    hints: ['Elon musk has a cameo in it','After credits scene contains first look at Mjolnir','Quote: Sir, I\'m gonna have to ask you to exit the donut.']},
    {title: 'Thor',
    image: "images/thor.jpg",
    hints: ['Hawkeye debut.','Base on norse mythology','Quote: Hammer! Hammer!']},
    {title: 'Captain America: The First Avenger',
    image: "images/captain-america-the-first-avenger.jpg",
    hints: ['The shield Captain America uses in the early stages of the film is similar to the one used in the first issue of the Captain America comic book.','The villain\'s name, "Johann Schmidt" is basically a German translation of the English name John Smith','Quote: Yeah. I knocked out Adolf Hitler over 200 times.']},
    {title: 'Avengers',
    image: "images/avengers.jpg",
    hints: ['First MCU movie to gross over $1 billion','Robert Downey Jr. kept food hidden all over the lab set.','Quote: We have a Hulk.']},
    {title: "Iron Man 3",
    image: "images/iron-man-3.jpg",
    hints: ['Directed by Shane Black.','Ends first MCU trilogy.','Quote: I\'m Tony Stark. I build neat stuff, got a great girl, occasionally save the world. So why can\'t I sleep?']},
    {title: 'Thor: The Dark World',
    image: "images/thor-the-dark-world.jpg",
    hints: [' Chris Hemsworth improvised hanging Mjölnir on a coat hook in a polite manner.','Chris Hemsworth grew out his hair for over a year to have more authentic long hair.','Quote: Well done, you just decapitated your grandfather!']},
    {title: 'Captain America: The Winter Soldier',
    image: "images/captain-america-the-winter-soldier.jpg",
    hints: ['First MCU movie directed by Russo brothers.','Chris Evans and Scarlett Johansson wrote their own dialogue for several scenes they had together.','Quote: Before we get started, does anyone want to get out?']},
    {title: "Guardians of the Galaxy",
    image: "images/guardians-of-the-galaxy.jpg",
    hints: ['Thanos almost got cut from the movie, but James Gunn decided to keep him for a connection to The Avengers.','"No raccoons or tree creatures were harmed during the making of this film."','Quote: I am Groot.']},
    {title: "Avengers: Age of Ultron",
    image: "images/avengers-age-of-ultron.jpg",
    hints: ['James Spader uses his natural speaking voice for main villain.','Scarlett Johansson was pregnant during filming.','Quote: Language!']},
    {title: "Ant Man",
    image: "images/ant-man.jpg",
    hints: ['Introduction of the smallest Avenger','When Paul Rudd told his nine-year-old son he was going to be Ant-Man, his son said, "Wow, I can\'t wait to see how stupid that\'ll be."','Quote: Wait I didn\'t steal anything! I was returning something I stole!']},
    {title: "Doctor Strange",
    image: "images/doctor-strange.jpg",
    hints: ['Morgan Freeman was considered for the role of The Ancient One.','Chiwetel Ejiofor is a fifth-degree black belt in karate, so his movements are second nature in fighting.','Quote: Dormammu, I\'ve come to bargain!']},
    {title: "Captain America: Civil War",
    image: "images/captain-america-civil-war.jpg",
    hints: ['Avengers 2.5','Chris Evans does a bicep curl, with a helicopter!','Quote: That shield doesn\'t belong to you. You don\'t deserve it! My father made that shield!']},
    {title: "Guardians of the Galaxy vol.2",
    image: "images/guardians-of-the-galaxy-vol2.jpg",
    hints: ['Movie starts with a dancing Groot','Taserface make-up took 2.5 to 3.5 hours to apply.','Quote: I\'m Mary Poppins, y\'all!']},
    {title: "Spider-man: Homecoming",
    image: "images/spiderman-homecoming.jpg",
    hints: ['The first Spider-Man film where Spider-Man has his iconic web wings from the comics.','Pictures of Howard Stark, Abraham Erskine, and Bruce Banner can be seen in Peter Parker\'s school.','Quote: I\'m... looking... at porn.']},
    {title: "Thor: Ragnarok",
    image: "images/thor-ragnarok.jpg",
    hints: ['Cate Blanchett accepted a role in this movie to please her children, who are Marvel comics fans.','Director Taika Waititi appeared in this movie as Korg.','Quote: I have been falling... for 30 minutes!']},
    {title: "Black Panther",
    image: "images/black-panther.jpg",
    hints: ['Michael B. Jordan was allowed to keep his Panther costume.','The name "Wakanda" comes from the Wakamba tribe of Kenya, also known as the Kamba.','Quote: I never freeze.']},
    {title: "Avengers: Infinity War",
    image: "images/avengers-infinity-war.jpg",
    hints: ['For the first time in Marvel Cinematic Universe history, Bruce Banner communicates directly with The Incredible Hulk.','Some actors weren\'t allowed to read the scipt.','Quote: You should have gone for the head.']},
    {title: "Ant Man and the Wasp",
    image: "images/ant-man-and-the-wasp.jpg",
    hints: ['This marks the second MCU film after Thor: Ragnarok to have a female as the leading antagonist.','Paul Rudd really did learn close up magic for this movie.','Quote: Anyone seen a Southern gentleman carrying a building?']},
    {title: "Captain Marvel",
    image: "images/captain-marvel.jpg",
    hints: ['The film was the first from the Marvel Cinematic Universe to have a female lead.','Goose is played by four different very professional cat actors.','Quote: Higher, further, faster, baby.']},
    {title: "Avengers: Endgame",
    image: "images/avengers-endgame.jpg",
    hints: ['Highest grossing MCU movie.','Robert Downey Jr. was the only actor who read the entire script.','Quote: Avengers! Assemble.']},
    {title: "Spider-man: Far From Home",
    image: "images/spiderman-far-from-home.jpg",
    hints: ['This is the first Marvel Studios movie without a cameo by Stan Lee.','The Netherlands tulip field scene was filmed in a grass field in the UK.','Quote: Bitch, please! You\'ve been to space.']},
    {title: "Black Widow",
    image: "images/black-widow.jpg",
    hints: ['First post pandemic MCU movie.','The first MCU film to be released in theatres and Disney+ simultaneously.','Quote: Such a poser.']},
    {title: "Shang-Chi and the Legend of the Ten Rings",
    image: "images/shang-chi-and-the-legend-of-the-ten-rings.jpg",
    hints: ['For her role as Katy, Awkwafina trained in car drifting and archery.','Simu Liu tweeted in December 2018 about asking Marvel for the role.','Quote: Calm down, mate! I\'m not dead, it\'s just a performance! Now get down here and play along!']},
    {title: "Eternals",
    image: "images/eternals.jpg",
    hints: ['Makkari is the first deaf superhero in the MCU.','Despite this film being a Marvel movie, two DC characters are mentioned.','Quote: When you love something, you protect it.']},
    {title: "Spider-Man: No Way Home",
    image: "images/spiderman-no-way-home.jpg",
    hints: ['Willem Dafoe went to the premiere wearing a green face mask.','Benedict Cumberbatch has admitted to not reading the full script, wanting to surprise himself with the final product.','Quote: And with great power, there must also come great responsibility.']},
    {title: "Doctor Strange in the Multiverse of Madness",
    image: "images/doctor-strange-in-the-multiverse-of-madness.jpg",
    hints: ['Elizabeth Olsen flew to London to work on this film just two days after she finished filming WandaVision.','Directed by Sam Raimi.','Quote: Dreamwalking, you hypocrite!']},
    {title: "Thor: Love and Thunder",
    image: "images/thor-love-and-thunder.jpg",
    hints: ['Korg\'s god Ninny-Nonny sits on a throne of scissors because in the Rock-Paper-Scissors game rock beats scissors.','Chris Hemsworth\'s family appears in this film.','Quote: EAT MY HAMMER!']},
    {title: "Black Panther: Wakanda Forever",
    image: "images/black-panther-wakanda-forever.jpg",
    hints: ['Tenoch Huerta didn\'t know how to swim.','The actors cast as Talokan learned a Mayan language for the film.','Quote: Only the most broken people can be great leaders.']},
];
